

services:
  supabase-db:
    image: supabase/postgres:15.1.0.70
    container_name: supabase-db
    ports:
      - "5438:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - supabase-data:/var/lib/postgresql/data

  supabase-auth:
    image: supabase/gotrue:v2.146.0
    container_name: supabase-auth
    ports:
      - "9999:9999"
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@supabase-db:5432/postgres
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - supabase-db

volumes:
  supabase-data:
